<?php

/**
 * Implementation of hook_init().
 */

function scroll_to_top_preprocess_page(&$variables)
{

    $theme = \Drupal::theme()->getActiveTheme()->getName();
    $admin_theme = \Drupal::config('system.theme')->get('admin');
    $config = \Drupal::config('scroll_to_top.settings');


    if ($config->get('scroll_to_top_enable_admin_theme') == TRUE || ($config->get('scroll_to_top_enable_admin_theme') == FALSE && ($theme != $admin_theme))) {

        $variables['#attached']['library'] = 'scroll_to_top/scroll_to_top_style';

        //building the css style
        $css = '';

        // Button position
        if ($config->get('scroll_to_top_position') == 1) {
            $css .= "#back-top { left:20px !important; }";
        }

        if ($config->get('scroll_to_top_position') == 2) {
            $css .= "#back-top { left:50% !important; margin:0px !important;}";
        }

        if ($config->get('scroll_to_top_position') == 3) {
            $css .= "#back-top { right:20px !important; }";
        }

        // Display label
        if ($config->get('scroll_to_top_display_text') == FALSE) {
            $css .= "span#link {display : none !important;}";
        } else {
            $css .= "";
        }

        // background color , hover , border
        $css .= "#back-top span#button { background-color: " . $config->get('scroll_to_top_bg_color_out', '#555555') . " !important;}";
        $css .= " #back-top span#button:hover {opacity:1;filter:alpha(opacity = 1) !important;background-color: " . $config->get('scroll_to_top_bg_color_hover', '#777777') . " !important;}";
        $css .= "#back-top span#button { border: 1px solid " . $config->get('scroll_to_top_bd_color', '#000000') . " !important;}";

        // button padding, border-radius, opacity
        $css .= "#back-top span#button { padding: " . $config->get('scroll_to_top_padding', '25px') . " !important;}";
        $css .= "#back-top span#button { border-radius: " . $config->get('scroll_to_top_bd_radius', '8px') . " !important;}";
        $css .= "#back-top span#button { opacity: " . $config->get('scroll_to_top_opacity', '0.8') . " !important;}";

        $variables['#attached']['html_head'][] = [
            [
                '#tag' => 'style',
                '#value' => $css,
            ],
            'css'
        ];
        $variables['#attached']['drupalSettings']['label'] = t($config->get('scroll_to_top_label'));

    }
}

