<?php

/**
 * @file
 * Provide scroll to top link.
 */

/**
 * Implementation of hook_init().
 */
/*
function scroll_to_top_preprocess_page(&$variables)
{

    $theme = \Drupal::theme()->getActiveTheme()->getName();
    $config =  \Drupal::config('scroll_to_top.settings');

    if ( $config->get('scroll_to_top_enable_admin_theme') == TRUE || ( $config->get('scroll_to_top_enable_admin_theme') == FALSE && ($theme !=  $config->get('admin_theme')))) {
        drupal_add_css(drupal_get_path('module', 'scroll_to_top') . '/scroll_to_top.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
        drupal_add_js(drupal_get_path('module', 'scroll_to_top') . '/scroll_to_top.js');
        drupal_add_js(array('scroll_to_top' => array('label' => t( $config->get('scroll_to_top_label', 'Back to top')))), 'setting');

        //building the css style
        $position = "";
        // Button position
        if ( $config->get('scroll_to_top_position', 1) == 1) {
            $position = "#back-top { right:40px; }";
        }
        if ( $config->get('scroll_to_top_position', 1) == 3) {
            $position = "#back-top { left:50%;margin:0px;}";
        }
        // Display label
        if ( $config->get('scroll_to_top_display_text', TRUE) == FALSE) {
            $display = "span#link {display : none;}";
        } else {
            $display = "";
        }
        // background color on hover
        $bgcolor = "#back-top span#button { background-color: " .  $config->get('scroll_to_top_bg_color_out', '#555555') . ";}";
        $bgcolor .= " #back-top span#button:hover {opacity:1;filter:alpha(opacity = 1);background-color: " .  $config->get('scroll_to_top_bg_color_hover', '#777777') . ";}";
        $css = $position;
        $css .= $bgcolor;
        $css .= $display;
        drupal_add_css($css, 'inline');
    }
}
*/